Restrict erlang function names to latin1 encoding
From https://www.erlang.org/doc/apps/stdlib/unicode_usage.html

> Erlang drivers and NIF-shared objects still cannot be named with names
> containing code points > 127. This limitation will be removed in a
> future release. However, Erlang modules can, but it is definitely not a
> good idea and is still considered experimental.

While I believe this refers to file-names this also seems to apply to
function names, otherwise you get:

    {:error, {:bad_lib, [70, 117, 110, 99, 116, 105, ...]}}

With this, if you try to do it, you get at compile-time the following
error:

    ❯ mix compile
    Compiling 1 file (.ex)
    Compiling crate nif in debug mode (native/nif)
       Compiling nif v0.1.0 (/home/rmk/programming/rust/rustler_raise_error/native/nif)
    error: custom attribute panicked
      --> src/lib.rs:76:1
       |
    76 | #[nif(name = "🧀")]
       | ^^^^^^^^^^^^^^^^^^^
       |
       = help: message: NIF names need to be Latin-1 encoded

    error[E0433]: failed to resolve: use of undeclared crate or module `cheese`
      --> src/lib.rs:90:9
       |
    90 |         cheese
       |         ^^^^^^ use of undeclared crate or module `cheese`

    For more information about this error, try `rustc --explain E0433`.
    error: could not compile `nif` due to 2 previous errors

    == Compilation error in file lib/nif.ex ==
    ** (RuntimeError) Rust NIF compile error (rustc exit code 101)
        (rustler 0.26.0) lib/rustler/compiler.ex:41: Rustler.Compiler.compile_crate/2
        lib/nif.ex:2: (module)